services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - ./config/credentials:/rails/config/credentials
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
