services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./bin/dev"
    tty: true
    volumes:
      - .:/rails
      - /rails/node_modules
      - ./config/credentials:/rails/config/credentials
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
